INSERT INTO Users (Name, Password, Email,UserGroup,IsSuperUser)  VALUES
('Gremlin Squarfish','simplepass','queece.b@apu.edu.my', 1,0),
('Mynas Opposite','simplepass','queece.b@apu.edu.my', 1,0),
('Jannider Snoutlick','simplepass','queece.b@apu.edu.my', 1,0),
('Dirt Stick','simplepass','queece.b@apu.edu.my', 1,0),
('Buckrain Politosh','simplepass','queece.b@apu.edu.my', 1,0),
('Fresident Freepaw Flitzen','simplepass','queece.b@apu.edu.my', 1,0),
('Azimuth Starcrack II','simplepass','queece.b@apu.edu.my', 1,0),
('Greek Baby','simplepass','queece.b@apu.edu.my', 1,0),
('Danny Sassoon','simplepass','queece.b@apu.edu.my', 1,0),
('Vodorok Pagina','simplepass','queece.b@apu.edu.my', 1,0),
('Biquinn Thunderhands Elfson','simplepass','queece.b@apu.edu.my', 1,0),
('Dunkrod Gluck','simplepass','queece.b@apu.edu.my', 1,0),
('Brockwyn 1000 Babies','simplepass','queece.b@apu.edu.my', 1,0),
('Exquizardus Sunset Mitchellham','simplepass','queece.b@apu.edu.my', 1,0),
('Ping Pong Leg','simplepass','queece.b@apu.edu.my', 1,0),
('Tootee Frootee','simplepass','queece.b@apu.edu.my', 1,0),
('Logan Hymen-Valencia','simplepass','queece.b@apu.edu.my', 1,0),
('Ronce Lafontaine','simplepass','queece.b@apu.edu.my', 1,0),
('Jeneric Tounguetaste','simplepass','queece.b@apu.edu.my', 1,0),
('Frizzy Totay','simplepass','queece.b@apu.edu.my', 1,0),
('Goblin!','simplepass','queece.b@apu.edu.my', 1,0),
('Rustrap D''Pencil','simplepass','queece.b@apu.edu.my', 1,0),
('Nacho Thigh-Juice','simplepass','queece.b@apu.edu.my', 1,0),
('Lemmicus D''Seuss','simplepass','queece.b@apu.edu.my', 1,0),
('Rorschach Tok-Tok','simplepass','queece.b@apu.edu.my', 1,0),
('Brick-Spunck Badgerballs','simplepass','queece.b@apu.edu.my', 1,0),
('Laporte Dipthong','simplepass','queece.b@apu.edu.my', 1,0),
('Boner P''Tiffy Jr.','simplepass','queece.b@apu.edu.my', 1,0),
('Horris Sophistofable','simplepass','queece.b@apu.edu.my', 1,0),
('Bark Bark Hoo Haw','simplepass','queece.b@apu.edu.my', 1,0),
('Lucifan Y. Sassafras','simplepass','queece.b@apu.edu.my', 1,0),
('Simon Asterisk','simplepass','queece.b@apu.edu.my', 1,0),
('Carlton The Seeker','simplepass','queece.b@apu.edu.my', 1,0),
('Shiprecc','simplepass','queece.b@apu.edu.my', 1,0),
('????','simplepass','queece.b@apu.edu.my', 1,0),
('Nogbone Danky','simplepass','queece.b@apu.edu.my', 1,0),
('Lavalamp Sequeltank','simplepass','queece.b@apu.edu.my', 1,0),
('Sir Amblin Flecator','simplepass','queece.b@apu.edu.my', 1,0),
('Hockbew Egress','simplepass','queece.b@apu.edu.my', 1,0),
('Gumbo Le Troutstain','simplepass','queece.b@apu.edu.my', 1,0),
('I1D1G53','simplepass','queece.b@apu.edu.my', 1,0),
('Busted-Lip Catharsises','simplepass','queece.b@apu.edu.my', 1,0),
('Steelgrippe D''Forte','simplepass','queece.b@apu.edu.my', 1,0);